name: Linting and Tests

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: amplium/git-crypt-action@master
        with:
          key_encoded: ${{ secrets.GIT_CRYPT_KEY }}
      - uses: php-actions/composer@v6
      - name: Run
        run: |
          make lint
          make tests
